input_data_path: "data/raw/train.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 17
train_params:
  model_type: "LogisticRegression"
feature_params:
  transformers:
    - PolynomialFeatures
  target_col: "condition"