on:
  push:
    branches:
      - hw1

jobs:
  my_checks:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: prepare requirements
      run: |
        make test_environment
        make requirements

    - name: Linter
      run: make lint

    - name: Tests
      run: python -m unittest

    - name: ls
      run: ls

    - name: Pipeline run
      run: python3 src/train_pipeline.py configs/train_config.yaml

